name: Publish Python Package

on:
  release:
    types: [published]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Python version for building/uploading

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Optional: Generate version file from GitHub tag
      # - name: Generate version file
      #   run: echo "__version__ = '${GITHUB_REF##refs/tags/}'" > your_package/_version.py

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
  